theme = 'hugo-theme-relearn'
baseURL = 'https://volteret4.github.io/music-fuzzy-doc'
relativeURLs = false
languageCode = 'es-ES'
title = 'mfuz'

[author]
  name = 'volteret4'
  email = 'frodobolson@disroot.org'
#  images = ['images/hero.png']

  

[params]
  disableLanguageSwitchingButton = true
  disableGeneratorVersion = true
  disableAssetsBusting = true # desactivar en prod.
  themeVariant = ['zen-dark', 'zen-light', 'relearn-light', 'relearn-dark']
  linkTitle = 'mfuz'

[outputs]
  home = ['html', 'rss', 'print']
  page = ['html', 'rss', 'print']
  section = ['html', 'rss', 'print']
